version: '3'
services:
    web:
        image: "app_web"
        build:
            context: .
            dockerfile: "Dockerfile"
        command: "tail -f /dev/null"
        environment:
          DATABASE_URL: psql://postgres:password@db/app
        env_file:
            - "./.env"
        volumes:
            - ".:/app"
            - "packages:/usr/local/lib/python3.7/site-packages/"
        ports:
            - "8000:8000"
        depends_on:
          - db
          - redis
          - webpack

    webpack:
        image: "app_web"
        command: "yarn dev"
        volumes:
            - ".:/app"
        tty: false
        stdin_open: false

    db:
        image: "postgres:alpine"
        environment:
            - "POSTGRES_USER=postgres"
            - "POSTGRES_PASSWORD=password"
        volumes:
            - "db:/var/lib/postgresql/data"
        ports:
            - "5432:5432"

    redis:
        image: "redis:5-alpine"
        volumes:
            - "redis-data:/data"


volumes:
    db:
        driver: local
    redis-data:
        driver: local
    packages:
        driver: local
