## Build and install packages
FROM python:3.7-alpine as build-python

RUN apk add --update --no-cache \
    build-base \
    tzdata \
    ca-certificates \
    gettext \
    libffi-dev \
    libxml2-dev \
    libxslt-dev \
    jpeg-dev \
    libjpeg-turbo-dev \
    libpng-dev \
	libwebp-dev \
	openjpeg-dev \
	tiff-dev \
	zlib-dev \
    postgresql-client \
    postgresql-dev \
    nodejs \
    yarn \
    && rm -rf /var/cache/apk/*


ENV SECRET_KEY=dummy
ENV DATABASE_URL=sqlite:///database.sqlite3
ENV CACHE_URL=dummycache://
ENV REDIS_URL=rediscache://127.0.0.1:6379/1
ENV EMAIL_URL=dummymail://

RUN mkdir -p /app
WORKDIR /app

COPY Pipfile Pipfile.lock /app/
COPY package.json yarn.lock /app/

RUN pip install --no-cache-dir --upgrade -q pip pipenv psycopg2
RUN pipenv install --system --dev
RUN yarn install --non-interactive --no-progress --ignore-optional

COPY . /app

RUN mkdir -p /app/run/media /app/run/static
RUN STATIC_URL=${STATIC_URL} python manage.py collectstatic --no-input

EXPOSE 8000
ENV PORT 8000
ENV PYTHONBUFFERED 1
ENV PROCESSES 4

CMD ["uwsgi", "--ini", "/app/settings/wsgi/uwsgi.ini"]

